---
#
# Usage: 
#
#
#   1) OpenVPN installation and configuration: 
#
#      ansible-playbook openvpn-setup.yml --ask-become-pass --extra-vars "hosts=< Ansible_target_hosts > openvpn_do_server_config=True"
#
#
#   2) OpenVPN installation and configuration: 
#
#      ansible-playbook openvpn-setup.yml --ask-become-pass --extra-vars "hosts=< Ansible_target_hosts > openvpn_gen_server_cert=True"
#
#
#
- hosts: "{{ hosts }}"

  vars:
      openvpn_server: ovpn.example.com
      openvpn_key_country: XX
      openvpn_key_province: YY
      openvpn_key_city: Sometown
      openvpn_key_org: example.com
      openvpn_key_email: noreply@example.com
      openvpn_key_ou: unit.example.com

  roles:
    - role: ~/ansible-role-openvpn
