---
#
# Usage: 
#
#   ansible-playbook openvpn-setup.yml --ask-become-pass --extra-vars "openvpn_gen_server_cert=True hosts=< Ansible_target_hosts >"
#

- hosts: "{{ hosts }}"

  roles:
    - role: ~/ansible-role-openvpn

      #####
      # This playbook target server,
      # disabling client certificate generation is not indicate
      #
      openvpn_gen_client_cert: False
      openvpn_do_server_config: True

      #####
      # openvpn_gen_server_cert, intentionally set to False
      # to prevent acidental server certificate regeneration
      #
      openvpn_gen_server_cert: False 

      openvpn_server: n.n.n.n
      openvpn_key_country: XX
      openvpn_key_province: YY
      openvpn_key_city: Sometown
      openvpn_key_org:  some.org
      openvpn_key_email: noreply@example.com
      openvpn_key_ou: vpn.some.org 
