---
- name: Push openvpn server.conf
  template:
    src: "{{ openvpn_server_dot_conf_file }}"
    dest: "/{{ openvpn_server_dot_conf_file }}"
    mode: u+rwx,go-rwx

- name: Push auth-user-pass-verify script ucn.pl
  template:
    src: "{{ openvpn_auth_user_pass_verify_script }}"
    dest: "/{{ openvpn_auth_user_pass_verify_script }}"
    mode: u+rwx,go-rwx

- name: Create client config dir
  file: path={{ openvpn_client_config_dir }} state=directory mode=0700

- name: Enable openvpn service
  service: name=openvpn enabled=yes

- name: Add CAP_AUDIT_WRITE to CapabilityBoundingSet in /{{ openvpn_systemd_service_patch_file }}
  shell: >
         sed --in-place 's/ CAP_AUDIT_WRITE//g;/^CapabilityBoundingSet=.*$/s/.*/& CAP_AUDIT_WRITE/' /{{ openvpn_systemd_service_patch_file }}
  tags:
    patch_openvpn_service

- name: Start openvpn service
  service: name=openvpn state=restarted
