---
- name: Update package cache
  apt: update_cache=yes
  #become: yes
  tags:
    - packages
    - server_config

- name: Install OpenVPN package
  apt: name={{item}} state=latest
  #become: yes
  tags:
    - packages
    - server_config
  with_items:
     - openvpn
     - easy-rsa
     - bridge-utils
     - zip
     - python-passlib
