---
- name: Prepare easy-rsa
  shell: >
         make-cadir {{ openvpn_easy_rsa_dir }}
  ignore_errors: yes
  tags:
    - server_certificate
    - certificates
    - easy-rsa

- name: Upload easy-rsa vars file
  template:
    src: "{{ openvpn_easy_rsa_vars_file }}"
    dest: "/{{ openvpn_easy_rsa_vars_file }}"
  tags:
    - server_certificate
    - certificates

- name: Server certificate I
  shell: >
         chdir={{ openvpn_easy_rsa_dir }}
         . {{ openvpn_easy_rsa_dir }}/vars  &&
         ./clean-all &&
         ./build-dh &&
         ./pkitool --initca &&
         ./pkitool --server server
  tags:
    - server_certificate
    - certificates

- name: Server certificate II
  shell: >
         chdir={{ openvpn_easy_rsa_dir }}/keys
         openvpn --genkey --secret ta.key &&
         cp server.crt server.key ca.crt dh2048.pem ta.key ../../
  tags:
    - server_certificate
    - certificates
