---
# tasks file for openvpn

- include: server-config.yml
  become: yes
  when: openvpn_do_server_config 

- include: certificates-generation.yml
  become: yes
  when: openvpn_gen_server_cert 

- include: openvpn-config.yml
  become: yes
  when: openvpn_do_server_config 
  tags: openvpn_config

- include: server-reboot.yml
  become: yes
  when: openvpn_gen_server_cert 

- include: client-cert-gen.yml
  become: yes
  when: openvpn_gen_client_cert
