---
#
# Usage: 
#
#   ansible-playbook create-client-cert.yml --ask-become-pass --extra-vars "hosts=< Ansible target hosts > openvpn_server=< OpenVPN hostname > openvpn_client_cert_name=< linux userid >"
#

- hosts: "{{ hosts }}"

  roles:
    - role: ~/ansible-role-openvpn
      openvpn_gen_client_cert: True
      openvpn_server: n.n.n.n
